// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOzv47SH2rGmqZFZaUMgGo5YRzMqDuavs',
    appId: '1:169301699653:web:8dbf01e487bd0e6517472c',
    messagingSenderId: '169301699653',
    projectId: 'cases-6661a',
    authDomain: 'cases-6661a.firebaseapp.com',
    storageBucket: 'cases-6661a.appspot.com',
    measurementId: 'G-034V0KTZ9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtEabBm36f_p0uSggeCshrP1Hsqqv4YaI',
    appId: '1:169301699653:android:7a163ff70f5028ef17472c',
    messagingSenderId: '169301699653',
    projectId: 'cases-6661a',
    storageBucket: 'cases-6661a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuZ4j5jUxfxD8He7NZAg0rwSx_1ymSLl0',
    appId: '1:169301699653:ios:25f4bdfa059cfaf417472c',
    messagingSenderId: '169301699653',
    projectId: 'cases-6661a',
    storageBucket: 'cases-6661a.appspot.com',
    iosBundleId: 'com.cher.cases',
  );

}